"""Fast sanity check for strategy.py, run between the implementer and the full WFO
grid search so a malformed edit fails in seconds instead of after a multi-minute run.

This is infrastructure, not strategy code — it is checked in once and reused every
iteration by /iterate-strategy, not regenerated by the strategy-implementer agent.
It is deliberately generic (it inspects signatures rather than hardcoding today's
param names) so it keeps working as strategy.py's params change across iterations.

Usage:
    /opt/anaconda3/envs/WFO/bin/python WFO-Trading/tools/check_strategy.py

Exit code 0 = all hard checks passed (warnings may still have printed).
Exit code 1 = at least one hard check failed; stderr explains which.
"""
import inspect
import os
import sys

# Make WFO-Trading/ importable regardless of cwd (this script lives in
# WFO-Trading/tools/, but strategy.py/wfo_engine.py/data_loader.py are top-level
# modules one directory up).
WFO_TRADING_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, WFO_TRADING_DIR)

import streamlit.logger
streamlit.logger.set_log_level("ERROR")  # silence st.cache_data noise outside `streamlit run`

failures: list[str] = []
warnings: list[str] = []


def fail(msg: str) -> None:
    failures.append(msg)


def warn(msg: str) -> None:
    warnings.append(msg)


# ---------------------------------------------------------------------------
# Check 1: generate_positions() honors the position contract on real data.
# ---------------------------------------------------------------------------
try:
    import strategy
    from data_loader import load_data

    if not hasattr(strategy, "DEFAULT_PARAMS"):
        fail("strategy.py has no DEFAULT_PARAMS dict — required so this check (and "
             "the WFO engine's retail-insample fallback) has a concrete param set to run.")
    else:
        df = load_data("local", "NQ", "1h").tail(1000)
        if df.empty:
            fail("no local NQ 1h data available to sanity-check against.")
        else:
            position = strategy.generate_positions(df, **strategy.DEFAULT_PARAMS)

            if list(position.index) != list(df.index):
                fail("generate_positions() output index doesn't match input index "
                     "(must return one value per input bar, same index).")

            if position.isna().any():
                fail(f"generate_positions() returned {int(position.isna().sum())} NaN "
                     "position value(s) — the Position Contract requires every bar to "
                     "resolve to a concrete -1/0/1 (apply_session_constraint* should "
                     "already fill gaps with 0/ffill; NaNs here mean that delegation "
                     "is missing or broken).")

            allowed = {-1.0, 0.0, 1.0}
            seen = set(position.dropna().unique().tolist())
            extra = seen - allowed
            if extra:
                fail(f"generate_positions() returned value(s) outside {{-1,0,1}}: "
                     f"{sorted(extra)} — violates the single-position contract (no "
                     "sizing, no pyramiding).")
except Exception as e:  # noqa: BLE001 — any exception here is itself the failure signal
    fail(f"generate_positions(**DEFAULT_PARAMS) raised {type(e).__name__}: {e}")

# ---------------------------------------------------------------------------
# Check 2: build_grid()'s output keys match generate_positions()'s signature —
# the actual mechanical lockstep check (not a prose reminder).
# ---------------------------------------------------------------------------
try:
    import wfo_engine

    gp_params = set(inspect.signature(strategy.generate_positions).parameters) - {"df"}
    bg_sig_names = list(inspect.signature(wfo_engine.build_grid).parameters.keys())

    # Map each build_grid() parameter to a concrete argument value derived from
    # DEFAULT_PARAMS: an exact name match is passed as-is (fixed param); a name
    # that is DEFAULT_PARAMS' key with a trailing grid-search "s" (donchian_n ->
    # donchian_ns, atr_mult -> atr_mults, target_mode -> target_modes) is passed
    # as a single-item list (grid-searched param).
    call_kwargs = {}
    unmapped = []
    for name in bg_sig_names:
        if name in strategy.DEFAULT_PARAMS:
            call_kwargs[name] = strategy.DEFAULT_PARAMS[name]
        else:
            stripped = name[:-1] if name.endswith("s") else name
            if stripped in strategy.DEFAULT_PARAMS:
                call_kwargs[name] = [strategy.DEFAULT_PARAMS[stripped]]
            else:
                unmapped.append(name)

    if unmapped:
        fail(f"could not derive a test value for build_grid() param(s) {unmapped} from "
             "DEFAULT_PARAMS — this happens exactly when params changed, which is "
             "exactly when this check matters most. Either name the new build_grid() "
             "param so it exact-matches a DEFAULT_PARAMS key (fixed param) or is that "
             "key plus a trailing 's' (grid-searched param), or update this script's "
             "mapping if the naming convention itself is changing.")
    else:
        grid = wfo_engine.build_grid(**call_kwargs)
        if not grid:
            fail("build_grid() produced an empty grid from DEFAULT_PARAMS-derived values.")
        else:
            for combo in grid:
                combo_keys = set(combo.keys())
                if combo_keys != gp_params:
                    missing = gp_params - combo_keys
                    extra = combo_keys - gp_params
                    fail(
                        "build_grid() output keys don't match generate_positions()'s "
                        f"signature — missing {sorted(missing) or '{}'}, "
                        f"unexpected {sorted(extra) or '{}'}. Update build_grid() (and "
                        "cli.py's matching flags) to stay in lockstep with "
                        "generate_positions()'s param list."
                    )
                    break  # one representative failure is enough

                if "session" not in combo_keys:
                    fail("a build_grid() combo is missing 'session' — it must always be "
                         "threaded through as a fixed param on every combo.")
                    break

                for k, v in combo.items():
                    if isinstance(v, int) and not isinstance(v, bool) and v > 500:
                        warn(f"build_grid() combo has {k}={v}, a suspiciously large int — "
                             "if this isn't a genuine bar-count lookback, pass it as a "
                             "float instead (wfo_engine._max_lookback_bars() treats every "
                             "int in the grid as a lookback when sizing the warm-up buffer).")
except Exception as e:  # noqa: BLE001
    fail(f"build_grid() lockstep check raised {type(e).__name__}: {e}")

# ---------------------------------------------------------------------------
# Check 3: cli.py doesn't reference a stale param key via best_params[...]/
# best_params.get(...) — the silent-corruption path. cli.py's fold-stability
# *print* block subscripts best_params directly (KeyError, loud) but the
# fold_rows CSV-writer uses .get() (returns None, silent) — a rename caught by
# the print block can still slip through the CSV writer undetected, and that
# CSV is exactly what wfo-evaluator reads for parameter-stability. Scoped to
# simple snake_case dict-key string literals immediately after an identifier
# (`p["donchian_n"]`, `f.best_params.get("donchian_n")`) — deliberately
# excludes bare list/tuple literals like `["channel"]` or `+ ["none"]`, which
# have no identifier directly before the bracket.
# ---------------------------------------------------------------------------
try:
    import re

    cli_src = open(os.path.join(WFO_TRADING_DIR, "cli.py")).read()
    subscript_keys = re.findall(r'\w\[\s*"([a-zA-Z_]\w*)"\s*\]', cli_src)
    get_keys = re.findall(r'\.get\(\s*"([a-zA-Z_]\w*)"', cli_src)
    referenced_keys = set(subscript_keys) | set(get_keys)

    stale = sorted(k for k in referenced_keys if k not in gp_params)
    if stale:
        fail(
            f"cli.py references dict key(s) {stale} via a subscript or .get() call, "
            f"but generate_positions()'s current param list is {sorted(gp_params)} — "
            "these look like stale references to a renamed/removed strategy param "
            "(most likely in the fold-param-stability block or the fold_rows CSV "
            "writer). The .get()-based ones won't crash, they'll silently write None "
            "into fold_table.csv — update cli.py's param references to match."
        )
except Exception as e:  # noqa: BLE001
    fail(f"cli.py lockstep check raised {type(e).__name__}: {e}")

# ---------------------------------------------------------------------------
# Check 4: no session-logic creep back into strategy.py.
# ---------------------------------------------------------------------------
try:
    strategy_src = open(os.path.join(WFO_TRADING_DIR, "strategy.py")).read()
    for banned in ("session_mask", "SESSION_CONFIG"):
        if banned in strategy_src:
            fail(f"strategy.py references '{banned}' directly — session-gating logic "
                 "must live only in session.py; delegate via apply_session_constraint() "
                 "or apply_session_constraint_with_stops() instead.")
except OSError as e:
    fail(f"could not read strategy.py to check for session-logic creep: {e}")

# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------
for w in warnings:
    print(f"WARNING: {w}", file=sys.stderr)

if failures:
    print(file=sys.stderr)
    for f in failures:
        print(f"FAIL: {f}", file=sys.stderr)
    print(f"\ncheck_strategy.py: {len(failures)} check(s) failed.", file=sys.stderr)
    sys.exit(1)

print("check_strategy.py: all checks passed" + (f" ({len(warnings)} warning(s))" if warnings else "") + ".")
sys.exit(0)
